Fix docs build: __funcs__ should contain function objects not strings
The docs generation script expects function objects in __funcs__ so it can
access func.__name__, but I had provided strings which caused:
AttributeError: 'str' object has no attribute '__name__'

Fixed by changing __funcs__ from string list to function object list.